title: AI4Bio Arxiv Daily
description: Automatically Update AI4Bio Papers Daily using Github Actions 
show_downloads: true

github:
  zip_url: https://github.com/dvlan26/daily-arxiv-ai4senser
  another_url: https://github.com/dvlan26/daily-arxiv-ai4senser

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: dvlan26

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
